# Change these first
owner: reduct-inc # Your GitHub organization or username, where this repository lives
repo: dev-status # The name of this repository

sites:
  - name: dev
    url: https://dev.distill.video
  - name: dev servers
    url: https://dev.distill.video/x/status
  - name: dev transcripts
    url: https://dev.distill.video/x/tsss/status
  - name: dev rendering
    url: https://dev.distill.video/x/render/status
  - name: dev live transcripts
    url: https://dev.distill.video/x/live-transcription/status
  - name: dev transcript processing
    url: https://dev.distill.video/x/whisper/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /dev-status
  logoUrl: https://raw.githubusercontent.com/reduct-inc/dev-status/61226e21b7a8a727d6de1e6c012503680afaeaa8/assets/reduct-logo-spacing.svg
  faviconSvg: https://raw.githubusercontent.com/reduct-inc/dev-status/0124ae685a090afd518bb6260b7732c47343a2fe/assets/reduct-logo.svg
  name: Reduct dev status page
  introTitle: "Real-time status data for Reduct dev:"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Updates
      href: https://github.com/$OWNER/$REPO/issues
  css: ".logo div { display: none } .submit-button { background: #949AB7; border-color: #3C45AB; } a.error-button { border-color: #3C45AB; background: #949AB7; } article.down-active { border-color: #EA4E3C; } article.down { border-left-color: #EA4E3C !important; } [aria-current] { border-bottom-color: #5B90F6; } nav { border-bottom-color: #BBBBBB; } section article.up:hover { filter: hue-rotate(65deg) drop-shadow(5px 5px 20px rgba(0, 0, 0, 0.07)); } section article.down:hover { filter: hue-rotate(65deg) drop-shadow(5px 5px 20px rgba(0, 0, 0, 0.07)); } section article.degraded:hover { filter: hue-rotate(65deg) drop-shadow(5px 5px 20px rgba(0, 0, 0, 0.07)); } canvas { filter: hue-rotate(65deg); } article.up { filter: hue-rotate(65deg); background-color: white; border-left-color: #58B99D !important; } article.down { filter: hue-rotate(65deg); background-color: white; border-left-color: #ff00ff !important; } article.degraded { filter: hue-rotate(65deg); background-color: white; border-left-color: #F73191 !important; } img.icon { display: none; } body { background-color: #F7F3EF; color: #3D3D3D; } article { background: #FFFFFF;} nav ul li { text-decoration-line: underline; text-decoration-thickness: 3px; text-decoration-color: #323B90; color: #323B90;}"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
